[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"

[etherscan]
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }